<?php

namespace App\Http\Controllers;

use App\Models\Appointment;
use App\Models\WorkSchedule;
use App\Models\ScheduleException;
use App\Models\ShiftTemplate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class StaffController extends Controller
{
    public function index()
    {
        $userId = Auth::id();
        $today = today();

        $myToday = Appointment::with(['customer', 'services'])
            ->where('user_id', $userId)
            ->whereDate('appointment_date', $today)
            ->whereIn('status', ['confirmed', 'pending', 'completed'])
            ->orderBy('start_time')
            ->get();

        $myUpcoming = Appointment::with(['customer', 'services'])
            ->where('user_id', $userId)
            ->whereDate('appointment_date', '>', $today)
            ->whereIn('status', ['confirmed', 'pending'])
            ->orderBy('appointment_date')
            ->orderBy('start_time')
            ->limit(10)
            ->get();

        // Today's revenue generated by this staff (from completed appointments)
        $todayRevenue = Appointment::where('user_id', $userId)
            ->whereDate('appointment_date', $today)
            ->where('status', 'completed')
            ->with('payments')
            ->get()
            ->sum(fn($appt) => $appt->payments->sum('amount'));

        // Weekly stats
        $weekStart = $today->copy()->startOfWeek();
        $weekEnd = $today->copy()->endOfWeek();
        
        $weeklyCompleted = Appointment::where('user_id', $userId)
            ->whereBetween('appointment_date', [$weekStart, $weekEnd])
            ->where('status', 'completed')
            ->count();

        $weeklyRevenue = Appointment::where('user_id', $userId)
            ->whereBetween('appointment_date', [$weekStart, $weekEnd])
            ->where('status', 'completed')
            ->with('payments')
            ->get()
            ->sum(fn($appt) => $appt->payments->sum('amount'));

        return view('staff-dashboard', compact(
            'myToday',
            'myUpcoming',
            'todayRevenue',
            'weeklyCompleted',
            'weeklyRevenue'
        ));
    }


    public function myAppointments(Request $request)
    {
        $query = Appointment::with(['customer', 'services'])
            ->where('user_id', Auth::id());

        if ($request->filled('date')) {
            $query->whereDate('appointment_date', $request->date);
        }

        $appointments = $query->orderBy('appointment_date', 'desc')
            ->orderBy('start_time')
            ->paginate(20);

        return view('staff.appointments', compact('appointments'));
    }

        public function mySchedule(Request $request)
    {
        $user = Auth::user();
        $weekStart = $request->get('week_start')
            ? Carbon::parse($request->get('week_start'))->startOfWeek()
            : now()->startOfWeek();

        $schedules = WorkSchedule::where('user_id', $user->id)
            ->get()
            ->keyBy('day_of_week');

        $exceptions = ScheduleException::where('user_id', $user->id)
            ->whereDate('exception_date', '>=', today())
            ->orderBy('exception_date')
            ->get();

        $days = [
            1 => ['Mon','Monday'], 2 => ['Tue','Tuesday'], 3 => ['Wed','Wednesday'],
            4 => ['Thu','Thursday'], 5 => ['Fri','Friday'], 6 => ['Sat','Saturday'], 0 => ['Sun','Sunday'],
        ];

        // Check if this user's schedule came from a template (best-effort hint)
        $templateHint = null;
        $hasSchedule = $schedules->isNotEmpty();
        if ($hasSchedule) {
            $templateHint = ShiftTemplate::where('is_active', true)->first()?->name;
        }

        return view('staff.schedule', compact(
            'user', 'schedules', 'exceptions', 'days', 'weekStart', 'templateHint'
        ));
    }

    /**
     * Staff: update their own weekly schedule (optional)
     */
    public function updateMySchedule(Request $request)
    {
        $user = Auth::user();
        $schedules = $request->input('schedules', []);

        foreach ($schedules as $dayNum => $data) {
            $isOff = isset($data['is_day_off']) && $data['is_day_off'] == '1';

            WorkSchedule::updateOrCreate(
                ['user_id' => $user->id, 'day_of_week' => $dayNum],
                [
                    'start_time' => $isOff ? null : ($data['start_time'] ?? '09:00'),
                    'end_time'   => $isOff ? null : ($data['end_time'] ?? '18:00'),
                    'is_day_off' => $isOff,
                ]
            );
        }

        return redirect()->route('staff.schedule')->with('success', 'Your schedule has been updated.');
    }
}